LineSub:
  topic_name: '/cam/line_img' # topic which contains line image

LineParams:
  threshold: 170 # threashold for binarizing the image
  width_of_line: 50 # estimate for width of line
  width_gain: 0.75 # percentage of the width_of_line to be used in calculating estimate for area and perimeter of the line

PlottingParams:
  arrow_scale: 50 # scale for size of arrow on image

CheckerboardParams:
  square_size: 0.028 # size of a side of a checkerboard square in meters
  car_body_frame_to_board: 0.25 # distance between the origin of the body frame of the car and the bottom side of the calibration board
